---
# tasks file for host_packages

- name: 'check if fzf is installed' 
  stat: path={{ fzf_install_path }}
  register: fzf_installed

- name: 'fzf: clone fzf repo'
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ fzf_install_path }}"
  when: not fzf_installed.stat.exists

- name: 'fzf: install packages'
  shell: "{{ fzf_install_path }}/install --bin"
  when: not fzf_installed.stat.exists

- name: 'fzf: config for users'
  template:
    dest: "~{{ item }}/.fzf.bash"
    src: fzf.bash.j2
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: "{{ fzf_userlist }}"

- name: 'fzf: config for users'
  blockinfile:
    path: "~{{ item }}/.bashrc"
    block: |
      [ -f ~/.fzf.bash ] && source ~/.fzf.bash
  with_items: "{{ fzf_userlist }}"

